version: '3.4'

services:
  identityserver:
    container_name: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=identityserverdb;Database=IdentityServer4;User Id=sa;Password=Your_Strong_Password;TrustServerCertificate=True;" 
    ports:
      - "8010:80"
    depends_on:
      - identityserverdb
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/C/Users/ContainerUser/AppData/Roaming/Microsoft/UserSecrets:ro
      - ${APPDATA}/ASP.NET/Https:/C/Users/ContainerUser/AppData/Roaming/ASP.NET/Https:ro
   
  identityserverdb:
    container_name: identityserverdb
    environment:
        SA_PASSWORD: "Your_Strong_Password"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"
    volumes:
      - identityserverdb:/var/opt/mssql


volumes:
  identityserverdb: