spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/catalogue
    username: username
    password: password

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public

server:
  port: 8181

