version: '3.4'

services:
  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile

  identityserverdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
