version: '3.8'

name: urban-vogue

services:

  api.geteway:
    container_name: api-gateway
    image: ${DOCKER_REGISTRY-}api-gateway


  catalogue.service:
    container_name: catalogue-service
    image: ${DOCKER_REGISTRY-}catalogue-service 


  catalogue.db:
    container_name: catalogue-db
    image: postgres:14.7-alpine
    

  identity.server:
    container_name: identity-server
    image: ${DOCKER_REGISTRY-}identity-server    


  identityserver.db:
    container_name: identity-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest


  pgadmin:
    container_name: catalogue-pgadmin
    image: dpage/pgadmin4:7    

  portainer:
    image: portainer/portainer-ce


  basket-service:
    build:
      dockerfile: Dockerfile
      context: ./basket-service
      target: production
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - SERVER_PORT=7777
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
    ports:
      - "7777:7777"

  redis:
    restart: always
    image: redis:alpine
    environment:
      - REDIS_ARGS=--requirepass password --save 20 1 --appendonly yes
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - redis:/var/lib/redis/data
    
  
volumes:
  catalogue-db-data:
  catalogue-pgadmin-data:
  redis:
  identity_server_db:
  catalogue-pgadmin-data:
  portainer_data:

