version: '3.8'
services:
  catalogue-service:
    image: catalogue-service:0.0.1
    build:
      context: ./catalogue-service/
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      catalogue-db:
        condition: service_healthy
    environment:
      - SERVER_PORT= 8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://catalogue-db/catalogue

  catalogue-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "books_db" ]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "15432:5432"
    volumes:
      - ./catalogue-service/infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - catalogue-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: catalogue-pgadmin
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - catalogue-pgadmin-data:/var/lib/pgadmin

  basket-service:
    build:
      dockerfile: Dockerfile
      context: ./basket-service
      target: production
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - SERVER_PORT=7777
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
    ports:
      - "7777:7777"

  redis:
    restart: always
    image: redis:alpine
    environment:
      - REDIS_ARGS=--requirepass password --save 20 1 --appendonly yes
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - redis:/var/lib/redis/data
    
  
volumes:
  catalogue-db-data:
  catalogue-pgadmin-data:
  redis:
