version: '3.8'
services:
  catalogue-service:
    image: catalogue-service:0.0.1
    build:
      context: ./catalogue-service/
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      catalogue-db:
        condition: service_healthy
    environment:
      - SERVER_PORT= 8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://catalogue-db/catalogue

  catalogue-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "books_db" ]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "15432:5432"
    volumes:
      - ./catalogue-service/infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - catalogue-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: catalogue-pgadmin
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - catalogue-pgadmin-data:/var/lib/pgadmin

volumes:
  catalogue-db-data:
  catalogue-pgadmin-data: